[package]
name = "detect"
version = "0.1.0"
edition = "2018"
authors = ["frag <francesco@amethix.com>"]
build = "build.rs"


[dependencies]
cpp = "0.5.4"
image = "0.23.4"

[build-dependencies]
cpp_build = "0.5.4"
reqwest = {version = "0.9.3", optional = true}
bzip2 = { version = "0.3.3", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"

[features]
default = []
download-models = ["reqwest", "bzip2"]
